name: Growing Devs
permalink: none
pygments: false
lsi: false
safe: true
exclude: ['tasks', '.ruby-version', 'README.md']
authors:
  -
    id: drjekyll
    name: Doctor Jekyll
  -
    id: tpitale
    name: Tony Pitale
